version: '3.3'
​
services:
  webpack:
    build: .
    command: npm run start:webpack
    volumes:
      - ./src:/usr/src/app/src:cached
      - ./public/dist:/usr/src/app/public/dist:cached
​
  seed:
    build: .
    command: npm run seed
    depends_on:
      - mongo
    links:
      - mongo
    environment:
      - MONGODB_URL=mongodb://bshawfriendbank:eqGfvqgLtaG8gV4@iad2-c13-0.mongo.objectrocket.com:53698,iad2-c13-1.mongo.objectrocket.com:53698,iad2-c13-2.mongo.objectrocket.com:53698/friendbank?replicaSet=14854e07ea3a49569994bf6ee6e47977
    env_file:
      - .env
​
  api:
    build: .
    command: npm run start:api
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URL=mongodb://bshawfriendbank:eqGfvqgLtaG8gV4@iad2-c13-0.mongo.objectrocket.com:53698,iad2-c13-1.mongo.objectrocket.com:53698,iad2-c13-2.mongo.objectrocket.com:53698/friendbank?replicaSet=14854e07ea3a49569994bf6ee6e47977
      - SEED_LOCALHOST_CAMPAIGN=true
      - DEBUG_CRM_SIGNUP=true
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src:cached
      - ./public/dist:/usr/src/app/public/dist:cached
​
  mongo:
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bshawfriendbank
      - MONGO_INITDB_ROOT_PASSWORD=eqGfvqgLtaG8gV4
    logging:
        driver: none
